#!/bin/sh
# run g++ on an input to see if it accepts it

if [ "$1" = "" ]; then
  echo "usage: $0 input.cc"
  exit 0
fi

if [ "$GCC" = "" ]; then
  GCC=$HOME/opt/gcc-3.4.3/bin/g++
fi

echo $GCC -o /dev/null -c -w -xc++ "$@"
exec $GCC -o /dev/null -c -w -xc++ "$@"
