#!/bin/sh
# run icc on an input to see if it accepts it

if [ "$1" = "" ]; then
  echo "usage: $0 input.cc"
  exit 0
fi

echo source $HOME/opt/intel/bin/iccvars.sh
source $HOME/opt/intel/bin/iccvars.sh

echo $HOME/opt/intel/bin/icpc -o /dev/null -c -xc++ -w "$@"
exec $HOME/opt/intel/bin/icpc -o /dev/null -c -xc++ -w "$@"
