# Makefile for in/
# produces some autogenerated tests

all: t0539


T0539 :=
T0539 += t0539_1.cc
T0539 += t0539_2.cc
T0539 += t0539_3.cc
T0539 += t0539_4.cc
T0539 += t0539_5.cc
T0539 += t0539_6.cc
T0539 += t0539_7.cc
T0539 += t0539_8.cc
T0539 += t0539_9.cc
T0539 += t0539_10.cc
T0539 += t0539_11.cc

.PHONY: t0539
t0539: $(T0539)

t0539_%.cc: t0539.cc
	rm -f $@
	cpp -C $^ -DSEL=$* >$@
	chmod a-w $@
