/*** builtin-definitions.c - generated by builtin-maker */
#include "builtin-t.h"

/** aio.c */

/** aliases.c */

/** alloca.c */
void * alloca (size_t size);
void * __builtin_alloca(size_t size) {
    return alloca(size);
}


/** argp.c */

/** argz.c */

/** arpa/inet.c */

/** arpa/nameser.c */

/** assert.c */

/** bits/byteswap.c */

/** bits/dlfcn.c */

/** bits/errno.c */

/** bits/libc-lock.c */

/** bits/sched.c */

/** bits/select.c */

/** bits/shm.c */

/** bits/siginfo.c */

/** bits/sigset.c */

/** bits/sigthread.c */

/** bits/socket.c */

/** bits/string2.c */

/** bits/string.c */

/** bits/stropts.c */

/** bits/sys_errlist.c */

/** bits/time.c */

/** complex.c */
double complex cacos (double complex z);
double complex __builtin_cacos(double complex z) {
    return cacos(z);
}

double complex casin (double complex z);
double complex __builtin_casin(double complex z) {
    return casin(z);
}

double complex catan (double complex z);
double complex __builtin_catan(double complex z) {
    return catan(z);
}

double complex ccos (double complex z);
double complex __builtin_ccos(double complex z) {
    return ccos(z);
}

double complex csin (double complex z);
double complex __builtin_csin(double complex z) {
    return csin(z);
}

double complex ctan (double complex z);
double complex __builtin_ctan(double complex z) {
    return ctan(z);
}

double complex cacosh (double complex z);
double complex __builtin_cacosh(double complex z) {
    return cacosh(z);
}

double complex casinh (double complex z);
double complex __builtin_casinh(double complex z) {
    return casinh(z);
}

double complex catanh (double complex z);
double complex __builtin_catanh(double complex z) {
    return catanh(z);
}

double complex ccosh (double complex z);
double complex __builtin_ccosh(double complex z) {
    return ccosh(z);
}

double complex csinh (double complex z);
double complex __builtin_csinh(double complex z) {
    return csinh(z);
}

double complex ctanh (double complex z);
double complex __builtin_ctanh(double complex z) {
    return ctanh(z);
}

double complex cexp (double complex z);
double complex __builtin_cexp(double complex z) {
    return cexp(z);
}

double complex clog (double complex z);
double complex __builtin_clog(double complex z) {
    return clog(z);
}

double complex cpow (double complex __x, double complex __y);
double complex __builtin_cpow(double complex __x, double complex __y) {
    return cpow(__x, __y);
}

double complex csqrt (double complex z);
double complex __builtin_csqrt(double complex z) {
    return csqrt(z);
}

double cabs (double complex z);
double __builtin_cabs(double complex z) {
    return cabs(z);
}

double carg (double complex z);
double __builtin_carg(double complex z) {
    return carg(z);
}

double complex conj (double complex z);
double complex __builtin_conj(double complex z) {
    return conj(z);
}

double complex cproj (double complex z);
double complex __builtin_cproj(double complex z) {
    return cproj(z);
}

double cimag (double complex z);
double __builtin_cimag(double complex z) {
    return cimag(z);
}

double creal (double complex z);
double __builtin_creal(double complex z) {
    return creal(z);
}

float complex cacosf (float complex z);
float complex __builtin_cacosf(float complex z) {
    return cacosf(z);
}

float complex casinf (float complex z);
float complex __builtin_casinf(float complex z) {
    return casinf(z);
}

float complex catanf (float complex z);
float complex __builtin_catanf(float complex z) {
    return catanf(z);
}

float complex ccosf (float complex z);
float complex __builtin_ccosf(float complex z) {
    return ccosf(z);
}

float complex csinf (float complex z);
float complex __builtin_csinf(float complex z) {
    return csinf(z);
}

float complex ctanf (float complex z);
float complex __builtin_ctanf(float complex z) {
    return ctanf(z);
}

float complex cacoshf (float complex z);
float complex __builtin_cacoshf(float complex z) {
    return cacoshf(z);
}

float complex casinhf (float complex z);
float complex __builtin_casinhf(float complex z) {
    return casinhf(z);
}

float complex catanhf (float complex z);
float complex __builtin_catanhf(float complex z) {
    return catanhf(z);
}

float complex ccoshf (float complex z);
float complex __builtin_ccoshf(float complex z) {
    return ccoshf(z);
}

float complex csinhf (float complex z);
float complex __builtin_csinhf(float complex z) {
    return csinhf(z);
}

float complex ctanhf (float complex z);
float complex __builtin_ctanhf(float complex z) {
    return ctanhf(z);
}

float complex cexpf (float complex z);
float complex __builtin_cexpf(float complex z) {
    return cexpf(z);
}

float complex clogf (float complex z);
float complex __builtin_clogf(float complex z) {
    return clogf(z);
}

float complex cpowf (float complex __x, float complex __y);
float complex __builtin_cpowf(float complex __x, float complex __y) {
    return cpowf(__x, __y);
}

float complex csqrtf (float complex z);
float complex __builtin_csqrtf(float complex z) {
    return csqrtf(z);
}

float cabsf (float complex z);
float __builtin_cabsf(float complex z) {
    return cabsf(z);
}

float cargf (float complex z);
float __builtin_cargf(float complex z) {
    return cargf(z);
}

float complex conjf (float complex z);
float complex __builtin_conjf(float complex z) {
    return conjf(z);
}

float complex cprojf (float complex z);
float complex __builtin_cprojf(float complex z) {
    return cprojf(z);
}

float cimagf (float complex z);
float __builtin_cimagf(float complex z) {
    return cimagf(z);
}

float crealf (float complex z);
float __builtin_crealf(float complex z) {
    return crealf(z);
}

long double complex cacosl (long double complex z);
long double complex __builtin_cacosl(long double complex z) {
    return cacosl(z);
}

long double complex casinl (long double complex z);
long double complex __builtin_casinl(long double complex z) {
    return casinl(z);
}

long double complex catanl (long double complex z);
long double complex __builtin_catanl(long double complex z) {
    return catanl(z);
}

long double complex ccosl (long double complex z);
long double complex __builtin_ccosl(long double complex z) {
    return ccosl(z);
}

long double complex csinl (long double complex z);
long double complex __builtin_csinl(long double complex z) {
    return csinl(z);
}

long double complex ctanl (long double complex z);
long double complex __builtin_ctanl(long double complex z) {
    return ctanl(z);
}

long double complex cacoshl (long double complex z);
long double complex __builtin_cacoshl(long double complex z) {
    return cacoshl(z);
}

long double complex casinhl (long double complex z);
long double complex __builtin_casinhl(long double complex z) {
    return casinhl(z);
}

long double complex catanhl (long double complex z);
long double complex __builtin_catanhl(long double complex z) {
    return catanhl(z);
}

long double complex ccoshl (long double complex z);
long double complex __builtin_ccoshl(long double complex z) {
    return ccoshl(z);
}

long double complex csinhl (long double complex z);
long double complex __builtin_csinhl(long double complex z) {
    return csinhl(z);
}

long double complex ctanhl (long double complex z);
long double complex __builtin_ctanhl(long double complex z) {
    return ctanhl(z);
}

long double complex cexpl (long double complex z);
long double complex __builtin_cexpl(long double complex z) {
    return cexpl(z);
}

long double complex clogl (long double complex z);
long double complex __builtin_clogl(long double complex z) {
    return clogl(z);
}

long double complex cpowl (long double complex __x, long double complex __y);
long double complex __builtin_cpowl(long double complex __x, long double complex __y) {
    return cpowl(__x, __y);
}

long double complex csqrtl (long double complex z);
long double complex __builtin_csqrtl(long double complex z) {
    return csqrtl(z);
}

long double cabsl (long double complex z);
long double __builtin_cabsl(long double complex z) {
    return cabsl(z);
}

long double cargl (long double complex z);
long double __builtin_cargl(long double complex z) {
    return cargl(z);
}

long double complex conjl (long double complex z);
long double complex __builtin_conjl(long double complex z) {
    return conjl(z);
}

long double complex cprojl (long double complex z);
long double complex __builtin_cprojl(long double complex z) {
    return cprojl(z);
}

long double cimagl (long double complex z);
long double __builtin_cimagl(long double complex z) {
    return cimagl(z);
}

long double creall (long double complex z);
long double __builtin_creall(long double complex z) {
    return creall(z);
}


/** crypt.c */

/** ctype.c */

/** dirent.c */

/** dlfcn.c */

/** envz.c */

/** err.c */

/** error.c */

/** execinfo.c */

/** fcntl.c */

/** fenv.c */

/** fmtmsg.c */

/** fnmatch.c */

/** fstab.c */

/** fts.c */

/** ftw.c */

/** getopt.c */

/** glob.c */

/** gnu/libc-version.c */

/** grp.c */

/** iconv.c */

/** ifaddrs.c */

/** inttypes.c */

/** langinfo.c */

/** libgen.c */

/** libintl.c */
char * gettext (const char *msgid);
char * __builtin_gettext(const char *msgid) {
    return gettext(msgid);
}

char * dgettext (const char *domainname, const char *msgid);
char * __builtin_dgettext(const char *domainname, const char *msgid) {
    return dgettext(domainname, msgid);
}

char * dcgettext (const char *domainname, __const char *msgid, int category);
char * __builtin_dcgettext(const char *domainname, __const char *msgid, int category) {
    return dcgettext(domainname, msgid, category);
}


/** link.c */

/** linux/kernel.c */

/** linux/security.c */

/** locale.c */

/** _main.c */

/** malloc.c */
__malloc_ptr_t malloc (size_t size);
__malloc_ptr_t __builtin_malloc(size_t size) {
    return malloc(size);
}

__malloc_ptr_t calloc (size_t nmemb, size_t size);
__malloc_ptr_t __builtin_calloc(size_t nmemb, size_t size) {
    return calloc(nmemb, size);
}


/** math.c */
double acos (double x);
double __builtin_acos(double x) {
    return acos(x);
}

double asin (double x);
double __builtin_asin(double x) {
    return asin(x);
}

double atan (double x);
double __builtin_atan(double x) {
    return atan(x);
}

double atan2 (double y, double x);
double __builtin_atan2(double y, double x) {
    return atan2(y, x);
}

double cos (double x);
double __builtin_cos(double x) {
    return cos(x);
}

double sin (double x);
double __builtin_sin(double x) {
    return sin(x);
}

double tan (double x);
double __builtin_tan(double x) {
    return tan(x);
}

double cosh (double x);
double __builtin_cosh(double x) {
    return cosh(x);
}

double sinh (double x);
double __builtin_sinh(double x) {
    return sinh(x);
}

double tanh (double x);
double __builtin_tanh(double x) {
    return tanh(x);
}

void sincos (double x, double *sinx, double *cosx);
void __builtin_sincos(double x, double *sinx, double *cosx) {
    sincos(x, sinx, cosx);
}

double acosh (double x);
double __builtin_acosh(double x) {
    return acosh(x);
}

double asinh (double x);
double __builtin_asinh(double x) {
    return asinh(x);
}

double atanh (double x);
double __builtin_atanh(double x) {
    return atanh(x);
}

double exp (double x);
double __builtin_exp(double x) {
    return exp(x);
}

double frexp (double x, int *exponent);
double __builtin_frexp(double x, int *exponent) {
    return frexp(x, exponent);
}

double ldexp (double x, int exponent);
double __builtin_ldexp(double x, int exponent) {
    return ldexp(x, exponent);
}

double log (double x);
double __builtin_log(double x) {
    return log(x);
}

double log10 (double x);
double __builtin_log10(double x) {
    return log10(x);
}

double modf (double x, double *iptr);
double __builtin_modf(double x, double *iptr) {
    return modf(x, iptr);
}

double exp10 (double x);
double __builtin_exp10(double x) {
    return exp10(x);
}

double pow10 (double x);
double __builtin_pow10(double x) {
    return pow10(x);
}

double expm1 (double x);
double __builtin_expm1(double x) {
    return expm1(x);
}

double log1p (double x);
double __builtin_log1p(double x) {
    return log1p(x);
}

double logb (double x);
double __builtin_logb(double x) {
    return logb(x);
}

double exp2 (double x);
double __builtin_exp2(double x) {
    return exp2(x);
}

double log2 (double x);
double __builtin_log2(double x) {
    return log2(x);
}

double pow (double x, double y);
double __builtin_pow(double x, double y) {
    return pow(x, y);
}

double sqrt (double x);
double __builtin_sqrt(double x) {
    return sqrt(x);
}

double hypot (double x, double y);
double __builtin_hypot(double x, double y) {
    return hypot(x, y);
}

double cbrt (double x);
double __builtin_cbrt(double x) {
    return cbrt(x);
}

double ceil (double x);
double __builtin_ceil(double x) {
    return ceil(x);
}

double fabs (double x);
double __builtin_fabs(double x) {
    return fabs(x);
}

double floor (double x);
double __builtin_floor(double x) {
    return floor(x);
}

double fmod (double x, double y);
double __builtin_fmod(double x, double y) {
    return fmod(x, y);
}

double drem (double x, double y);
double __builtin_drem(double x, double y) {
    return drem(x, y);
}

double significand (double x);
double __builtin_significand(double x) {
    return significand(x);
}

double copysign (double x, double y);
double __builtin_copysign(double x, double y) {
    return copysign(x, y);
}

double nan (const char *tagb);
double __builtin_nan(const char *tagb) {
    return nan(tagb);
}

double j0 (double x);
double __builtin_j0(double x) {
    return j0(x);
}

double j1 (double x);
double __builtin_j1(double x) {
    return j1(x);
}

double jn (int n, double x);
double __builtin_jn(int n, double x) {
    return jn(n, x);
}

double y0 (double x);
double __builtin_y0(double x) {
    return y0(x);
}

double y1 (double x);
double __builtin_y1(double x) {
    return y1(x);
}

double yn (int n, double x);
double __builtin_yn(int n, double x) {
    return yn(n, x);
}

double erf (double x);
double __builtin_erf(double x) {
    return erf(x);
}

double erfc (double x);
double __builtin_erfc(double x) {
    return erfc(x);
}

double lgamma (double x);
double __builtin_lgamma(double x) {
    return lgamma(x);
}

double tgamma (double x);
double __builtin_tgamma(double x) {
    return tgamma(x);
}

double gamma (double x);
double __builtin_gamma(double x) {
    return gamma(x);
}

double rint (double x);
double __builtin_rint(double x) {
    return rint(x);
}

double nextafter (double x, double y);
double __builtin_nextafter(double x, double y) {
    return nextafter(x, y);
}

double nexttoward (double x, long double y);
double __builtin_nexttoward(double x, long double y) {
    return nexttoward(x, y);
}

double remainder (double x, double y);
double __builtin_remainder(double x, double y) {
    return remainder(x, y);
}

double scalbn (double x, int n);
double __builtin_scalbn(double x, int n) {
    return scalbn(x, n);
}

int ilogb (double x);
int __builtin_ilogb(double x) {
    return ilogb(x);
}

double scalbln (double x, long int n);
double __builtin_scalbln(double x, long int n) {
    return scalbln(x, n);
}

double nearbyint (double x);
double __builtin_nearbyint(double x) {
    return nearbyint(x);
}

double round (double x);
double __builtin_round(double x) {
    return round(x);
}

double trunc (double x);
double __builtin_trunc(double x) {
    return trunc(x);
}

double remquo (double x, double y, int *quo);
double __builtin_remquo(double x, double y, int *quo) {
    return remquo(x, y, quo);
}

long int lrint (double x);
long int __builtin_lrint(double x) {
    return lrint(x);
}

long long int llrint (double x);
long long int __builtin_llrint(double x) {
    return llrint(x);
}

long int lround (double x);
long int __builtin_lround(double x) {
    return lround(x);
}

long long int llround (double x);
long long int __builtin_llround(double x) {
    return llround(x);
}

double fdim (double x, double y);
double __builtin_fdim(double x, double y) {
    return fdim(x, y);
}

double fmax (double x, double y);
double __builtin_fmax(double x, double y) {
    return fmax(x, y);
}

double fmin (double x, double y);
double __builtin_fmin(double x, double y) {
    return fmin(x, y);
}

double fma (double x, double y, double z);
double __builtin_fma(double x, double y, double z) {
    return fma(x, y, z);
}

double scalb (double x, double n);
double __builtin_scalb(double x, double n) {
    return scalb(x, n);
}

float acosf (float x);
float __builtin_acosf(float x) {
    return acosf(x);
}

float asinf (float x);
float __builtin_asinf(float x) {
    return asinf(x);
}

float atanf (float x);
float __builtin_atanf(float x) {
    return atanf(x);
}

float atan2f (float y, float x);
float __builtin_atan2f(float y, float x) {
    return atan2f(y, x);
}

float cosf (float x);
float __builtin_cosf(float x) {
    return cosf(x);
}

float sinf (float x);
float __builtin_sinf(float x) {
    return sinf(x);
}

float tanf (float x);
float __builtin_tanf(float x) {
    return tanf(x);
}

float coshf (float x);
float __builtin_coshf(float x) {
    return coshf(x);
}

float sinhf (float x);
float __builtin_sinhf(float x) {
    return sinhf(x);
}

float tanhf (float x);
float __builtin_tanhf(float x) {
    return tanhf(x);
}

void sincosf (float x, float *sinx, float *cosx);
void __builtin_sincosf(float x, float *sinx, float *cosx) {
    sincosf(x, sinx, cosx);
}

float acoshf (float x);
float __builtin_acoshf(float x) {
    return acoshf(x);
}

float asinhf (float x);
float __builtin_asinhf(float x) {
    return asinhf(x);
}

float atanhf (float x);
float __builtin_atanhf(float x) {
    return atanhf(x);
}

float expf (float x);
float __builtin_expf(float x) {
    return expf(x);
}

float frexpf (float x, int *exponent);
float __builtin_frexpf(float x, int *exponent) {
    return frexpf(x, exponent);
}

float ldexpf (float x, int exponent);
float __builtin_ldexpf(float x, int exponent) {
    return ldexpf(x, exponent);
}

float logf (float x);
float __builtin_logf(float x) {
    return logf(x);
}

float log10f (float x);
float __builtin_log10f(float x) {
    return log10f(x);
}

float modff (float x, float *iptr);
float __builtin_modff(float x, float *iptr) {
    return modff(x, iptr);
}

float exp10f (float x);
float __builtin_exp10f(float x) {
    return exp10f(x);
}

float pow10f (float x);
float __builtin_pow10f(float x) {
    return pow10f(x);
}

float expm1f (float x);
float __builtin_expm1f(float x) {
    return expm1f(x);
}

float log1pf (float x);
float __builtin_log1pf(float x) {
    return log1pf(x);
}

float logbf (float x);
float __builtin_logbf(float x) {
    return logbf(x);
}

float exp2f (float x);
float __builtin_exp2f(float x) {
    return exp2f(x);
}

float log2f (float x);
float __builtin_log2f(float x) {
    return log2f(x);
}

float powf (float x, float y);
float __builtin_powf(float x, float y) {
    return powf(x, y);
}

float sqrtf (float x);
float __builtin_sqrtf(float x) {
    return sqrtf(x);
}

float hypotf (float x, float y);
float __builtin_hypotf(float x, float y) {
    return hypotf(x, y);
}

float cbrtf (float x);
float __builtin_cbrtf(float x) {
    return cbrtf(x);
}

float ceilf (float x);
float __builtin_ceilf(float x) {
    return ceilf(x);
}

float fabsf (float x);
float __builtin_fabsf(float x) {
    return fabsf(x);
}

float floorf (float x);
float __builtin_floorf(float x) {
    return floorf(x);
}

float fmodf (float x, float y);
float __builtin_fmodf(float x, float y) {
    return fmodf(x, y);
}

float dremf (float x, float y);
float __builtin_dremf(float x, float y) {
    return dremf(x, y);
}

float significandf (float x);
float __builtin_significandf(float x) {
    return significandf(x);
}

float copysignf (float x, float y);
float __builtin_copysignf(float x, float y) {
    return copysignf(x, y);
}

float nanf (const char *tagb);
float __builtin_nanf(const char *tagb) {
    return nanf(tagb);
}

float j0f (float x);
float __builtin_j0f(float x) {
    return j0f(x);
}

float j1f (float x);
float __builtin_j1f(float x) {
    return j1f(x);
}

float jnf (int n, float x);
float __builtin_jnf(int n, float x) {
    return jnf(n, x);
}

float y0f (float x);
float __builtin_y0f(float x) {
    return y0f(x);
}

float y1f (float x);
float __builtin_y1f(float x) {
    return y1f(x);
}

float ynf (int n, float x);
float __builtin_ynf(int n, float x) {
    return ynf(n, x);
}

float erff (float x);
float __builtin_erff(float x) {
    return erff(x);
}

float erfcf (float x);
float __builtin_erfcf(float x) {
    return erfcf(x);
}

float lgammaf (float x);
float __builtin_lgammaf(float x) {
    return lgammaf(x);
}

float tgammaf (float x);
float __builtin_tgammaf(float x) {
    return tgammaf(x);
}

float gammaf (float x);
float __builtin_gammaf(float x) {
    return gammaf(x);
}

float rintf (float x);
float __builtin_rintf(float x) {
    return rintf(x);
}

float nextafterf (float x, float y);
float __builtin_nextafterf(float x, float y) {
    return nextafterf(x, y);
}

float nexttowardf (float x, long double y);
float __builtin_nexttowardf(float x, long double y) {
    return nexttowardf(x, y);
}

float remainderf (float x, float y);
float __builtin_remainderf(float x, float y) {
    return remainderf(x, y);
}

float scalbnf (float x, int n);
float __builtin_scalbnf(float x, int n) {
    return scalbnf(x, n);
}

int ilogbf (float x);
int __builtin_ilogbf(float x) {
    return ilogbf(x);
}

float scalblnf (float x, long int n);
float __builtin_scalblnf(float x, long int n) {
    return scalblnf(x, n);
}

float nearbyintf (float x);
float __builtin_nearbyintf(float x) {
    return nearbyintf(x);
}

float roundf (float x);
float __builtin_roundf(float x) {
    return roundf(x);
}

float truncf (float x);
float __builtin_truncf(float x) {
    return truncf(x);
}

float remquof (float x, float y, int *quo);
float __builtin_remquof(float x, float y, int *quo) {
    return remquof(x, y, quo);
}

long int lrintf (float x);
long int __builtin_lrintf(float x) {
    return lrintf(x);
}

long long int llrintf (float x);
long long int __builtin_llrintf(float x) {
    return llrintf(x);
}

long int lroundf (float x);
long int __builtin_lroundf(float x) {
    return lroundf(x);
}

long long int llroundf (float x);
long long int __builtin_llroundf(float x) {
    return llroundf(x);
}

float fdimf (float x, float y);
float __builtin_fdimf(float x, float y) {
    return fdimf(x, y);
}

float fmaxf (float x, float y);
float __builtin_fmaxf(float x, float y) {
    return fmaxf(x, y);
}

float fminf (float x, float y);
float __builtin_fminf(float x, float y) {
    return fminf(x, y);
}

float fmaf (float x, float y, float z);
float __builtin_fmaf(float x, float y, float z) {
    return fmaf(x, y, z);
}

float scalbf (float x, float n);
float __builtin_scalbf(float x, float n) {
    return scalbf(x, n);
}

long double acosl (long double x);
long double __builtin_acosl(long double x) {
    return acosl(x);
}

long double asinl (long double x);
long double __builtin_asinl(long double x) {
    return asinl(x);
}

long double atanl (long double x);
long double __builtin_atanl(long double x) {
    return atanl(x);
}

long double atan2l (long double y, long double x);
long double __builtin_atan2l(long double y, long double x) {
    return atan2l(y, x);
}

long double cosl (long double x);
long double __builtin_cosl(long double x) {
    return cosl(x);
}

long double sinl (long double x);
long double __builtin_sinl(long double x) {
    return sinl(x);
}

long double tanl (long double x);
long double __builtin_tanl(long double x) {
    return tanl(x);
}

long double coshl (long double x);
long double __builtin_coshl(long double x) {
    return coshl(x);
}

long double sinhl (long double x);
long double __builtin_sinhl(long double x) {
    return sinhl(x);
}

long double tanhl (long double x);
long double __builtin_tanhl(long double x) {
    return tanhl(x);
}

void sincosl (long double x, long double *sinx, long double *cosx);
void __builtin_sincosl(long double x, long double *sinx, long double *cosx) {
    sincosl(x, sinx, cosx);
}

long double acoshl (long double x);
long double __builtin_acoshl(long double x) {
    return acoshl(x);
}

long double asinhl (long double x);
long double __builtin_asinhl(long double x) {
    return asinhl(x);
}

long double atanhl (long double x);
long double __builtin_atanhl(long double x) {
    return atanhl(x);
}

long double expl (long double x);
long double __builtin_expl(long double x) {
    return expl(x);
}

long double frexpl (long double x, int *exponent);
long double __builtin_frexpl(long double x, int *exponent) {
    return frexpl(x, exponent);
}

long double ldexpl (long double x, int exponent);
long double __builtin_ldexpl(long double x, int exponent) {
    return ldexpl(x, exponent);
}

long double logl (long double x);
long double __builtin_logl(long double x) {
    return logl(x);
}

long double log10l (long double x);
long double __builtin_log10l(long double x) {
    return log10l(x);
}

long double modfl (long double x, long double *iptr);
long double __builtin_modfl(long double x, long double *iptr) {
    return modfl(x, iptr);
}

long double exp10l (long double x);
long double __builtin_exp10l(long double x) {
    return exp10l(x);
}

long double pow10l (long double x);
long double __builtin_pow10l(long double x) {
    return pow10l(x);
}

long double expm1l (long double x);
long double __builtin_expm1l(long double x) {
    return expm1l(x);
}

long double log1pl (long double x);
long double __builtin_log1pl(long double x) {
    return log1pl(x);
}

long double logbl (long double x);
long double __builtin_logbl(long double x) {
    return logbl(x);
}

long double exp2l (long double x);
long double __builtin_exp2l(long double x) {
    return exp2l(x);
}

long double log2l (long double x);
long double __builtin_log2l(long double x) {
    return log2l(x);
}

long double powl (long double x, long double y);
long double __builtin_powl(long double x, long double y) {
    return powl(x, y);
}

long double sqrtl (long double x);
long double __builtin_sqrtl(long double x) {
    return sqrtl(x);
}

long double hypotl (long double x, long double y);
long double __builtin_hypotl(long double x, long double y) {
    return hypotl(x, y);
}

long double cbrtl (long double x);
long double __builtin_cbrtl(long double x) {
    return cbrtl(x);
}

long double ceill (long double x);
long double __builtin_ceill(long double x) {
    return ceill(x);
}

long double fabsl (long double x);
long double __builtin_fabsl(long double x) {
    return fabsl(x);
}

long double floorl (long double x);
long double __builtin_floorl(long double x) {
    return floorl(x);
}

long double fmodl (long double x, long double y);
long double __builtin_fmodl(long double x, long double y) {
    return fmodl(x, y);
}

long double dreml (long double x, long double y);
long double __builtin_dreml(long double x, long double y) {
    return dreml(x, y);
}

long double significandl (long double x);
long double __builtin_significandl(long double x) {
    return significandl(x);
}

long double copysignl (long double x, long double y);
long double __builtin_copysignl(long double x, long double y) {
    return copysignl(x, y);
}

long double nanl (const char *tagb);
long double __builtin_nanl(const char *tagb) {
    return nanl(tagb);
}

long double j0l (long double x);
long double __builtin_j0l(long double x) {
    return j0l(x);
}

long double j1l (long double x);
long double __builtin_j1l(long double x) {
    return j1l(x);
}

long double jnl (int n, long double x);
long double __builtin_jnl(int n, long double x) {
    return jnl(n, x);
}

long double y0l (long double x);
long double __builtin_y0l(long double x) {
    return y0l(x);
}

long double y1l (long double x);
long double __builtin_y1l(long double x) {
    return y1l(x);
}

long double ynl (int n, long double x);
long double __builtin_ynl(int n, long double x) {
    return ynl(n, x);
}

long double erfl (long double x);
long double __builtin_erfl(long double x) {
    return erfl(x);
}

long double erfcl (long double x);
long double __builtin_erfcl(long double x) {
    return erfcl(x);
}

long double lgammal (long double x);
long double __builtin_lgammal(long double x) {
    return lgammal(x);
}

long double tgammal (long double x);
long double __builtin_tgammal(long double x) {
    return tgammal(x);
}

long double gammal (long double x);
long double __builtin_gammal(long double x) {
    return gammal(x);
}

long double rintl (long double x);
long double __builtin_rintl(long double x) {
    return rintl(x);
}

long double nextafterl (long double x, long double y);
long double __builtin_nextafterl(long double x, long double y) {
    return nextafterl(x, y);
}

long double nexttowardl (long double x, long double y);
long double __builtin_nexttowardl(long double x, long double y) {
    return nexttowardl(x, y);
}

long double remainderl (long double x, long double y);
long double __builtin_remainderl(long double x, long double y) {
    return remainderl(x, y);
}

long double scalbnl (long double x, int n);
long double __builtin_scalbnl(long double x, int n) {
    return scalbnl(x, n);
}

int ilogbl (long double x);
int __builtin_ilogbl(long double x) {
    return ilogbl(x);
}

long double scalblnl (long double x, long int n);
long double __builtin_scalblnl(long double x, long int n) {
    return scalblnl(x, n);
}

long double nearbyintl (long double x);
long double __builtin_nearbyintl(long double x) {
    return nearbyintl(x);
}

long double roundl (long double x);
long double __builtin_roundl(long double x) {
    return roundl(x);
}

long double truncl (long double x);
long double __builtin_truncl(long double x) {
    return truncl(x);
}

long double remquol (long double x, long double y, int *quo);
long double __builtin_remquol(long double x, long double y, int *quo) {
    return remquol(x, y, quo);
}

long int lrintl (long double x);
long int __builtin_lrintl(long double x) {
    return lrintl(x);
}

long long int llrintl (long double x);
long long int __builtin_llrintl(long double x) {
    return llrintl(x);
}

long int lroundl (long double x);
long int __builtin_lroundl(long double x) {
    return lroundl(x);
}

long long int llroundl (long double x);
long long int __builtin_llroundl(long double x) {
    return llroundl(x);
}

long double fdiml (long double x, long double y);
long double __builtin_fdiml(long double x, long double y) {
    return fdiml(x, y);
}

long double fmaxl (long double x, long double y);
long double __builtin_fmaxl(long double x, long double y) {
    return fmaxl(x, y);
}

long double fminl (long double x, long double y);
long double __builtin_fminl(long double x, long double y) {
    return fminl(x, y);
}

long double fmal (long double x, long double y, long double z);
long double __builtin_fmal(long double x, long double y, long double z) {
    return fmal(x, y, z);
}

long double scalbl (long double x, long double n);
long double __builtin_scalbl(long double x, long double n) {
    return scalbl(x, n);
}

double huge_val (void);
double __builtin_huge_val(void) {
    return huge_val();
}

float huge_valf (void);
float __builtin_huge_valf(void) {
    return huge_valf();
}

long double huge_vall (void);
long double __builtin_huge_vall(void) {
    return huge_vall();
}

double inf (void);
double __builtin_inf(void) {
    return inf();
}

float inff (void);
float __builtin_inff(void) {
    return inff();
}

long double infl (void);
long double __builtin_infl(void) {
    return infl();
}

double nans (const char *str);
double __builtin_nans(const char *str) {
    return nans(str);
}

float nansf (const char *str);
float __builtin_nansf(const char *str) {
    return nansf(str);
}

long double nansl (const char *str);
long double __builtin_nansl(const char *str) {
    return nansl(str);
}


/** mcheck.c */

/** mntent.c */

/** monetary.c */
ssize_t vstrfmon (char * s, size_t maxsize, const char * format, __builtin_va_list args);
ssize_t __builtin_strfmon(char * s, size_t maxsize, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    ssize_t ret = vstrfmon(s, maxsize, format, args);
    __builtin_va_end(args);
    return ret;
}


/** netdb.c */

/** net/if.c */

/** netinet/ether.c */

/** netinet/in.c */

/** nl_types.c */

/** nss.c */

/** obstack.c */

/** printf.c */

/** pthread.c */

/** pty.c */

/** pwd.c */

/** regex.c */

/** regexp.c */

/** resolv.c */

/** rpc/auth.c */

/** rpc/auth_des.c */

/** rpc/auth_unix.c */

/** rpc/clnt.c */

/** rpc/des_crypt.c */

/** rpc/key_prot.c */

/** rpc/netdb.c */

/** rpc/pmap_clnt.c */

/** rpc/pmap_prot.c */

/** rpc/pmap_rmt.c */

/** rpc/rpc.c */

/** rpc/rpc_msg.c */

/** rpc/svc_auth.c */

/** rpcsvc/bootparam_prot.c */

/** rpc/svc.c */

/** rpcsvc/key_prot.c */

/** rpcsvc/klm_prot.c */

/** rpcsvc/mount.c */

/** rpcsvc/nfs_prot.c */

/** rpcsvc/nis.c */

/** rpcsvc/nis_callback.c */

/** rpcsvc/nislib.c */

/** rpcsvc/nlm_prot.c */

/** rpcsvc/rex.c */

/** rpcsvc/rquota.c */

/** rpcsvc/rstat.c */

/** rpcsvc/rusers.c */

/** rpcsvc/sm_inter.c */

/** rpcsvc/spray.c */

/** rpcsvc/yp.c */

/** rpcsvc/ypclnt.c */

/** rpcsvc/yppasswd.c */

/** rpcsvc/yp_prot.c */

/** rpcsvc/ypupd.c */

/** rpc/xdr.c */

/** sched.c */

/** search.c */

/** semaphore.c */

/** setjmp.c */

/** sgtty.c */

/** shadow.c */

/** signal.c */

/** spawn.c */

/** stdio.c */
int vfprintf (FILE * stream, const char * format, __builtin_va_list args);
int __builtin_fprintf(FILE * stream, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vfprintf(stream, format, args);
    __builtin_va_end(args);
    return ret;
}

int vfprintf_unlocked (FILE * stream, const char * format, __builtin_va_list args);
int __builtin_fprintf_unlocked(FILE * stream, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vfprintf_unlocked(stream, format, args);
    __builtin_va_end(args);
    return ret;
}

int vprintf (const char * format, __builtin_va_list args);
int __builtin_printf(const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vprintf(format, args);
    __builtin_va_end(args);
    return ret;
}

int vprintf_unlocked (const char * format, __builtin_va_list args);
int __builtin_printf_unlocked(const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vprintf_unlocked(format, args);
    __builtin_va_end(args);
    return ret;
}

int vsprintf (char * s, const char * format, __builtin_va_list args);
int __builtin_sprintf(char * s, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vsprintf(s, format, args);
    __builtin_va_end(args);
    return ret;
}

int vfprintf (FILE * s, const char * format, va_list arg);
int __builtin_vfprintf(FILE * s, const char * format, va_list arg) {
    return vfprintf(s, format, arg);
}

int vprintf (const char * format, va_list arg);
int __builtin_vprintf(const char * format, va_list arg) {
    return vprintf(format, arg);
}

int vsprintf (char * s, const char * format, va_list arg);
int __builtin_vsprintf(char * s, const char * format, va_list arg) {
    return vsprintf(s, format, arg);
}

int vsnprintf (char * s, size_t maxlen, const char * format, __builtin_va_list args);
int __builtin_snprintf(char * s, size_t maxlen, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vsnprintf(s, maxlen, format, args);
    __builtin_va_end(args);
    return ret;
}

int vsnprintf (char * s, size_t maxlen, const char * format, va_list arg);
int __builtin_vsnprintf(char * s, size_t maxlen, const char * format, va_list arg) {
    return vsnprintf(s, maxlen, format, arg);
}

int vfscanf (FILE * stream, const char * format, __builtin_va_list args);
int __builtin_fscanf(FILE * stream, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vfscanf(stream, format, args);
    __builtin_va_end(args);
    return ret;
}

int vscanf (const char * format, __builtin_va_list args);
int __builtin_scanf(const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vscanf(format, args);
    __builtin_va_end(args);
    return ret;
}

int vsscanf (const char * s, const char * format, __builtin_va_list args);
int __builtin_sscanf(const char * s, const char * format, ...) {
    __builtin_va_list args;
    __builtin_va_start(args, format);
    int ret = vsscanf(s, format, args);
    __builtin_va_end(args);
    return ret;
}

int vfscanf (FILE * s, const char * format, va_list arg);
int __builtin_vfscanf(FILE * s, const char * format, va_list arg) {
    return vfscanf(s, format, arg);
}

int vscanf (const char * format, va_list arg);
int __builtin_vscanf(const char * format, va_list arg) {
    return vscanf(format, arg);
}

int vsscanf (const char * s, const char * format, va_list arg);
int __builtin_vsscanf(const char * s, const char * format, va_list arg) {
    return vsscanf(s, format, arg);
}

int fputc (int c, FILE *stream);
int __builtin_fputc(int c, FILE *stream) {
    return fputc(c, stream);
}

int putchar (int c);
int __builtin_putchar(int c) {
    return putchar(c);
}

int putchar_unlocked (int c);
int __builtin_putchar_unlocked(int c) {
    return putchar_unlocked(c);
}

int fputs (const char * s, FILE * stream);
int __builtin_fputs(const char * s, FILE * stream) {
    return fputs(s, stream);
}

int puts (const char *__s);
int __builtin_puts(const char *__s) {
    return puts(__s);
}

int puts_unlocked (const char *__s);
int __builtin_puts_unlocked(const char *__s) {
    return puts_unlocked(__s);
}

size_t fwrite (const void * ptr, size_t size, size_t n, FILE * s);
size_t __builtin_fwrite(const void * ptr, size_t size, size_t n, FILE * s) {
    return fwrite(ptr, size, n, s);
}

int fputs_unlocked (const char * s, FILE * stream);
int __builtin_fputs_unlocked(const char * s, FILE * stream) {
    return fputs_unlocked(s, stream);
}

size_t fwrite_unlocked (const void * ptr, size_t size, size_t n, FILE * stream);
size_t __builtin_fwrite_unlocked(const void * ptr, size_t size, size_t n, FILE * stream) {
    return fwrite_unlocked(ptr, size, n, stream);
}


/** stdio_ext.c */

/** stdlib.c */
void abort (void);
void __builtin_abort(void) {
    abort();
}

void exit (int status);
void __builtin_exit(int status) {
    exit(status);
}

void _Exit (int status);
void __builtin__Exit(int status) {
    _Exit(status);
}

int abs (int x);
int __builtin_abs(int x) {
    return abs(x);
}

long int labs (long int x);
long int __builtin_labs(long int x) {
    return labs(x);
}

long long int llabs (long long int x);
long long int __builtin_llabs(long long int x) {
    return llabs(x);
}


/** string.c */
void * memcpy (void * dest, void const * src, size_t n);
void * __builtin_memcpy(void * dest, void const * src, size_t n) {
    return memcpy(dest, src, n);
}

void * memmove (void * dest, const void * src, size_t n);
void * __builtin_memmove(void * dest, const void * src, size_t n) {
    return memmove(dest, src, n);
}

void * memset (void * s, int c, size_t n);
void * __builtin_memset(void * s, int c, size_t n) {
    return memset(s, c, n);
}

int memcmp (const void * s1, const void * s2, size_t n);
int __builtin_memcmp(const void * s1, const void * s2, size_t n) {
    return memcmp(s1, s2, n);
}

char * strcpy (char * dest, const char * src);
char * __builtin_strcpy(char * dest, const char * src) {
    return strcpy(dest, src);
}

char * strncpy (char * dest, const char * src, size_t n);
char * __builtin_strncpy(char * dest, const char * src, size_t n) {
    return strncpy(dest, src, n);
}

char * strcat (char * dest, const char * src);
char * __builtin_strcat(char * dest, const char * src) {
    return strcat(dest, src);
}

char * strncat (char * dest, const char * src, size_t n);
char * __builtin_strncat(char * dest, const char * src, size_t n) {
    return strncat(dest, src, n);
}

int strcmp (const char * s1, const char * s2);
int __builtin_strcmp(const char * s1, const char * s2) {
    return strcmp(s1, s2);
}

int strncmp (const char * s1, const char * s2, size_t n);
int __builtin_strncmp(const char * s1, const char * s2, size_t n) {
    return strncmp(s1, s2, n);
}

char * strdup (const char * s1);
char * __builtin_strdup(const char * s1) {
    return strdup(s1);
}

char * strchr (const char * s, int c);
char * __builtin_strchr(const char * s, int c) {
    return strchr(s, c);
}

char * strrchr (const char * s, int c);
char * __builtin_strrchr(const char * s, int c) {
    return strrchr(s, c);
}

size_t strcspn (const char * s, const char * reject);
size_t __builtin_strcspn(const char * s, const char * reject) {
    return strcspn(s, reject);
}

size_t strspn (const char * s, const char * accept);
size_t __builtin_strspn(const char * s, const char * accept) {
    return strspn(s, accept);
}

char * strpbrk (const char * s, const char * accept);
char * __builtin_strpbrk(const char * s, const char * accept) {
    return strpbrk(s, accept);
}

char * strstr (const char * haystack, const char * needle);
char * __builtin_strstr(const char * haystack, const char * needle) {
    return strstr(haystack, needle);
}

void * mempcpy (void * dest, const void * src, size_t n);
void * __builtin_mempcpy(void * dest, const void * src, size_t n) {
    return mempcpy(dest, src, n);
}

size_t strlen (const char * s);
size_t __builtin_strlen(const char * s) {
    return strlen(s);
}

void bzero (void * s, size_t n);
void __builtin_bzero(void * s, size_t n) {
    bzero(s, n);
}

void bcopy (const void * src, void * dest, size_t n);
void __builtin_bcopy(const void * src, void * dest, size_t n) {
    bcopy(src, dest, n);
}

int bcmp (const void * s1, const void * s2, size_t n);
int __builtin_bcmp(const void * s1, const void * s2, size_t n) {
    return bcmp(s1, s2, n);
}

char * index (const char * s, int c);
char * __builtin_index(const char * s, int c) {
    return index(s, c);
}

char * rindex (const char * s, int c);
char * __builtin_rindex(const char * s, int c) {
    return rindex(s, c);
}

int ffs (int i);
int __builtin_ffs(int i) {
    return ffs(i);
}

int ffsl (long int l);
int __builtin_ffsl(long int l) {
    return ffsl(l);
}

int ffsll (long long int ll);
int __builtin_ffsll(long long int ll) {
    return ffsll(ll);
}

char * stpcpy (char * dest, const char * src);
char * __builtin_stpcpy(char * dest, const char * src) {
    return stpcpy(dest, src);
}


/** stropts.c */

/** sys/acct.c */

/** sys/epoll.c */

/** sys/file.c */

/** sys/fsuid.c */

/** sys/gmon.c */

/** sys/io.c */

/** sys/ioctl.c */

/** sys/ipc.c */

/** sys/kdaemon.c */

/** sys/klog.c */

/** sys/mman.c */

/** sys/mount.c */

/** sys/msg.c */

/** sys/perm.c */

/** sys/personality.c */

/** sys/poll.c */

/** sys/prctl.c */

/** sys/profil.c */

/** sys/ptrace.c */

/** sys/quota.c */

/** sys/reboot.c */

/** sys/resource.c */

/** sys/select.c */

/** sys/sem.c */

/** sys/sendfile.c */

/** sys/shm.c */

/** sys/socket.c */

/** sys/stat.c */

/** sys/statfs.c */

/** sys/statvfs.c */

/** sys/swap.c */

/** sys/sysctl.c */

/** sys/sysinfo.c */

/** sys/syslog.c */

/** sys/sysmacros.c */

/** sys/timeb.c */

/** sys/time.c */

/** sys/times.c */

/** sys/timex.c */

/** sys/uio.c */

/** sys/ustat.c */

/** sys/utsname.c */

/** sys/vlimit.c */

/** sys/vm86.c */

/** sys/vtimes.c */

/** sys/wait.c */

/** sys/xattr.c */

/** termios.c */

/** thread_db.c */

/** time.c */
size_t strftime (char * s, size_t maxsize, const char * format, const struct tm * tp);
size_t __builtin_strftime(char * s, size_t maxsize, const char * format, const struct tm * tp) {
    return strftime(s, maxsize, format, tp);
}


/** ttyent.c */

/** ucontext.c */

/** ulimit.c */

/** unistd.c */

/** utime.c */

/** utmp.c */

/** utmpx.c */

/** wchar.c */

/** wctype.c */

/** wordexp.c */
